version: '3'

services:
  node:
    container_name: alarm_node
    build:
      context: ./node/
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ${MOUNT_VOLUME}:/app/
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    container_name: alarm_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
    command: --init-file="/docker-entrypoint-initdb.d/create_table.sql" --default-authentication-plugin=mysql_native_password
    ports:
      - "${HOST_MYSQL_PORT}:${CONTAINER_MYSQL_PORT}"
    volumes:
      - "${MYSQL_DATA_PATH}:/var/lib/mysql:delegated"
      - "./mysql/init/:/docker-entrypoint-initdb.d/"
      - "${MYSQL_ENV_CONF_PATH}:/etc/mysql/conf.d"
      - "${MYSQL_DUMP_PATH}:/dumpdata"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}